# Generated by Django 5.0.3 on 2024-04-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_disciplina_gradecurricular_turma_aula_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
